export const START_DRAGGING_TASK = 'startDraggingTask'
export const CHANGE_TASK_POSITION = 'changeTaskPosition'
export const CREATE_NEW_TASK = 'createNewTask'
export const START_DRAGGING_CATEGORY = 'startDraggingCategory'
export const CHANGE_CATEGORY_POSITION = 'changeCategoryPosition'
export const CHANGE_ACTIVE_DROPZONE = 'changeActiveDropZone'
export const START_NEW_TASK_PROCESS = 'startNewTaskProcess'
